figure(1),plot([f_alpha_beta.' f_alpha_beta_LT.'])
hold, plot(pilot,0,'r*')
title('alpha-beta')
legend('SP1','LT')
figure(2)
plot([f_beta.' f_beta_LT.'])
hold on, plot(pilot,0,'r*')
legend('SP1','LT')
title('beta')
figure(3)
plot((1:Ns)',[f_alpha.' f_alpha_LT.'])
hold on, plot(pilot,0,'r*')
legend('SP1','LT')
title('alpha')

figure(4),plot([PmeanT+phase_shift Pmean_LTT+phase_shift u_exact.'] )
title('alpha-beta')
legend('PmeanT','Pmean-LTT','u-exact')
figure(6)
plot((1:Ns)',[[parameters1{:,1}].'+phase_shift [parameters1_LT{:,1}].'+phase_shift u_exact_alpha.'] )
legend('Pmean','Pmean-LT','u-exact')
title('alpha')
figure(5)
plot([[parameters2{:,1}].'+phase_shift [parameters2_LT{:,1}].'+phase_shift u_exact_beta.'] )
legend('Pmean','Pmean-LT','u-exact')
title('beta')